### PR TITLE
Add vpa

### PR DESCRIPTION
**Pull request by QuentinBisson**

### CODE REVIEW

**Comment by QuentinBisson** [comment]
Running fine on gremlin:

image

But there is not a lot of movements there. I'm waiting for https://github.com/giantswarm/giantswarm/issues/25410 to be over before I can try on other MCs.

My plan would be to release it on all MCs, see how it's going, especially on bigger ones as this is also enabling PDBs and if that works, release it everywhere, otherwise revert :)

**Comment by QuantumEnigmaa** [comment]
What's the difference between this PR and https://github.com/giantswarm/vertical-pod-autoscaler-app/pull/153 ?

**Comment by QuentinBisson** [comment]
This one adds VPA and PDBs to your PR :D

**Comment by QuantumEnigmaa** [comment]
But isn't a vpa object created automatically by the updater when the recommander and the admission-controller have triggered it ?

**Comment by QuentinBisson** [comment]
No, VPA cannot create pods, that is something goldilocks does :)

**Comment by QuantumEnigmaa** [comment]
Oh ok !

**Comment by QuantumEnigmaa** [comment]
So this PR is to enable VPA to scale itself ?

**Comment by QuentinBisson** [comment]
Yes :)

**Review by QuantumEnigmaa — APPROVED** [review]
This will enhance the vpa behemoth for sure. Can't wait to have those changes in my PR :)

**Comment by QuentinBisson** [comment]
Closing in favor of https://github.com/giantswarm/vertical-pod-autoscaler-app/pull/163

**Pull request closed without merging**
