### PR TITLE
Added the use of the runtime/default seccomp profile.

### PR DESCRIPTION
**Pull request by Strigix**
I've modified the container and pod securitycontexts to let this application make use of the runtime/default seccomp profile. During testing this did not seem to interrupt any functionality. Please confirm this if possible.
This is done in light of:

https://github.com/giantswarm/roadmap/issues/259

Drop a message on slack if you've got questions.

### CODE REVIEW

**Comment by QuentinBisson** [comment]
Hey @Strigix, sorry but could you rebase your branch? VPA changed a bit since the last time

**Comment by Strigix** [comment]
@QuentinBisson 
I've done a rebase. 

Would you be okay with finishing this for me? I'm not entirely sure where to apply the seccomp profiles in this application and I don't want to risk breaking it.

**Comment by QuantumEnigmaa** [comment]
I think you should have updated the `updater`, `recommender` and `admission-controller` sections which are located under the `vertical-pod-autoscaler` sections instead of creating new ones since we are using chart dependency.

**Comment by QuentinBisson** [comment]
Tested

**Pull request merged**
