### PR TITLE
Add pod Annotation for `cluster-autoscaler safe-to-evict`

### PR DESCRIPTION
**Pull request by primeroz**
Towards https://github.com/giantswarm/vodafone/issues/617

Add `cluster-autoscaler` `safe-to-evict` annotation to `recommender` and `updater` pods
so that , since we run those pods in kube-system, they will be evicted by cluster-autoscaler
if a node needs to be reclaimed

### CODE REVIEW

**Review by QuentinBisson — APPROVED** [review]

**Comment by QuantumEnigmaa** [comment]
Why adding this annotation only to `updater` and `recommender` and not to `admission-controller` as well ?

**Comment by QuentinBisson** [comment]
I would think it's because the admission-controller has a pdb?

**Comment by primeroz** [comment]
> I would think it's because the admission-controller has a pdb?
yes the webhook is a multi replica pod so it has a pdb and so is good

the updater and recommender are single pod , so no pdb so they get the annotation

**Comment by QuantumEnigmaa** [comment]
Ok ok good for me :)

**Review by QuantumEnigmaa — APPROVED** [review]

**Pull request merged**
