### PR TITLE
Add new observability recommender with 0.3 margin fraction

### PR DESCRIPTION
**Pull request by TheoBrigitte**
Towards: https://github.com/giantswarm/giantswarm/issues/31385

This PR adds a new recommender with a different `margin-fraction` setting of 0.3 instead of the 0.15 default value.
The `margin-fraction` setting is `Fraction of usage added as the safety margin to the recommended request (default 0.15)`, see https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/FAQ.md#what-are-the-parameters-to-vpa-recommender

This is aiming at reducing the number of restarts happening when observability components are scaling up. Usually many restarts are happening since the resources needs to be increased many times until reaching the right value, this is to me a sign that resources increase steps are too small in those cases. 

I did deploy this on a test installation, but test are meaningless until we have this on real world scenarios.

All the files added in this PR where taken directly from the upstream chart then I basically change the section for [extra args](https://github.com/giantswarm/vertical-pod-autoscaler-app/pull/321/files#diff-c7a6a43fdcf4d03a81e43e6e3b1ee93a255b66894b729560acdefc0b50140754R64-R66) and added a new section in the values file.

### CODE REVIEW

**Comment by Gacko** [comment]
Can you elaborate on why we cannot just use another instance of the VPA app with all the other components turned off?

**Review by Gacko — CHANGES_REQUESTED** [review]
See above.

**Comment by TheoBrigitte** [comment]
Using another instance of VPA app is currently not possible as there will be a conflict due to the CRDs being installed by the dependency chart.

**Comment by Gacko** [comment]
We have a separate app for installing VPA CRDs which is installed before this VPA app here. The VPA CRD app applies them directly from the `templates` folder, so they get the VPA CRD app is their owner in the first step.

The VPA app here uses a `kubectl apply` job to install the same CRDs, so the annotations should not change. We also added a job to this VPA app here that removes the Helm annotations from CRDs after installing or upgrading it.

So ideally the VPA CRDs do not have a Helm release owning it and there should not be an issue with a second instance of the VPA app.

Nevertheless we moved to using upstream as a dependency for good reasons. Adding a copy of something that's included in upstream would in my opinion go in the wrong direction and make all the efforts worthless. So we should rather try to make the whole CRD component switchable in upstream. The same goes for the other components. I just checked and it could be we also need to add a switch to disable the other components.

Feel free to leave an issue on our board so we can move this discussion to a more appropriate place.

**Pull request closed without merging**
