### PR TITLE
Make VPA Kyverno Policy compliant , this is so we can enforce kyverno policies

### PR DESCRIPTION
**Pull request by primeroz**
Towards https://github.com/giantswarm/roadmap/issues/2533

### CODE REVIEW

**Review by hervenicol — APPROVED** [review]
LGTM if tested.

**Review by njuettner — APPROVED** [review]

**Comment by njuettner** [comment]
Just one note, I think it would make sense to update the schema gen for helm.

**Review by njuettner — COMMENTED** [review]
Another thing, sorry do we need the kyverno policy exception additionally? I think I saw them added in more and more repos.

**Comment by primeroz** [comment]
> Another thing, sorry do we need the kyverno policy exception additionally? I think I saw them added in more and more repos.

No because with those changes the pods should be compliant with the actual kyverno policy. the exceptions are added when , for example, you can't drop the capabilities and so you need to make `an exception for this workload` . Does it make sense ?

**Comment by primeroz** [comment]
> LGTM if tested.

Tested on CAPI workload cluster , worked as expected. 

I will test it on a MC so i can confirm it does clear the Kyverno policies ( since kyverno does not run on WC yet )

**Comment by primeroz** [comment]
once applied on glippy the policies stop failing

image

**Comment by QuentinBisson** [comment]
Can you test in another provider, mainly vintage?

**Comment by primeroz** [comment]
> Can you test in another provider, mainly vintage?

sure can, do you have any preference ?

**Comment by QuentinBisson** [comment]
Preferably an aws MC and WC just to be sure we are not breaking anything

**Comment by primeroz** [comment]
Working OK on vintage AWS WC

**Comment by primeroz** [comment]
Working OK on vintage AWS MC ( Gauss )

**Pull request merged**
